name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build APK
        run:  ./gradlew -p android assembleDebug

      - name: Find APK
        run: |
              echo "Searching for APK files..."
              find . -type f -name "*.apk" -print
   
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
           name: app-debug
           path: "*/.apk"
           if-no-files-found: error
        
